apiVersion: v1
kind: Service
metadata:
  name: mancenter-svc
spec:
  type: NodePort
  selector:
    app: management-center
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
    nodePort: 30082
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: management-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/management-center
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: MC_CONTEXT
            value: /mancenter

